adding resolver

diff --git a/adduptocron b/adduptocron
--- a/adduptocron
+++ b/adduptocron
@@ -16,39 +16,19 @@
 _srcsbinpath=$(dirname $(readlink -f $0))
 _srchomepath=$(dirname $_srcsbinpath) 
 
-function confirmtogo(){
-	local _conit _valtogo _msg
-	_msg=$1
-	_valtogo=$2
-	if [ -z "$_msg" ] ; then
+declare -a _requiredfiles
+declare -a _requiredexefiles
+
+_requiredfiles[${#_requiredfiles[@]}]="functions"
+
+if [ ! -z "$_srcsbinpath" ] ; then
+	if [ -s "$_srcsbinpath/resolve" ] ; then
+		. $_srcsbinpath/resolve	
+	else
+		echo "$_srcsbinpath/resolve file not found!" 1>&2
 		exit 1
 	fi
-	read -p "$_msg" _conit
-	_conit=${_conit,,}
-	if [ -z "$_valtogo" ] ; then
-		_valtogo="yes"
-	else
-		_valtogo=${_valtogo,,}
-	fi
-	if [ "$_valtogo" = "notempty" ] ; then
-		if [ ! -z "$_conit" ] ; then
-			echo "$_conit"
-			return 0
-		else
-			return 1
-		fi
-	elif [ "$_valtogo" = "pathexist" ] ; then
-		if [ -e "$_conit" ] ; then
-			echo "$_conit"
-			return 0
-		else
-			return 1
-		fi
-	elif [ ! -z "$_conit" ] && [ "$_conit" = "$_valtogo" ] ; then
-		return 0
-	fi
-	return 1
-}
+fi
 
 _hour=$1
 _defauthour=0
diff --git a/upgradespy b/upgradespy
--- a/upgradespy
+++ b/upgradespy
@@ -15,67 +15,23 @@
 
 _srcsbinpath=$(dirname $(readlink -f $0))
 
-_miscpath=""
-function addmiscpath(){
-	local _var _com _comloc
-	_com=$1
-	_var="_${1}"
-	_comloc=$2
-	if [ -z "$_comloc" ] || [ ! -x "$_comloc" ]; then 
-		_comloc=$(command -v "$_com")
-	fi
-	if [ -z "$_comloc" ] ; then
-		echo "	ERROR: linux-misc/$_com command not found in your system. Please install it from https://github.com/helal00/linux-misc before continue. If the command is already installed, plese specify it in $_miscpath with adding a line as '$_var=/path/to/$_com'. Create the file if doesn't exist already."
-		return 1
-	else		
-		if ! grep -Fq "$_var=" "$_miscpath" ; then
-			sed -i -e '$a\' "$_miscpath"
-			echo "$_var=$_comloc" >> "$_miscpath"
-		fi
-		echo "$_comloc"
-	fi
-	return 0
-}
+declare -a _requiredfiles
+declare -a _requiredexefiles
 
-if [ ! -z "$_srcsbinpath" ]; then
-	_miscpath="$_srcsbinpath/linux-misc"
-	if [ -s "$_miscpath" ] ; then
-		. "$_miscpath"
-	fi
-	
-	if ! _calloutput=$(addmiscpath "getgitrepo" "$_getgitrepo") ; then
-		echo "$_calloutput" 1>&2
-		exit 1
-	else
-		_getgitrepo="$_calloutput"
-	fi
+_requiredfiles[${#_requiredfiles[@]}]="functions"
+_requiredexefiles[${#_requiredexefiles[@]}]="getgitrepo"
+_requiredexefiles[${#_requiredexefiles[@]}]="githublatest"
+_requiredexefiles[${#_requiredexefiles[@]}]="sflatest"
+_requiredexefiles[${#_requiredexefiles[@]}]="timeout3"
 
-	if ! _calloutput=$(addmiscpath "githublatest" "$_githublatest") ; then
-		echo "$_calloutput" 1>&2
-		exit 1
+if [ ! -z "$_srcsbinpath" ] ; then
+	if [ -s "$_srcsbinpath/resolve" ] ; then
+		. $_srcsbinpath/resolve	
 	else
-		_githublatest="$_calloutput"
-	fi
-	
-	if ! _calloutput=$(addmiscpath "sflatest" "$_sflatest") ; then
-		echo "$_calloutput" 1>&2
+		echo "$_srcsbinpath/resolve file not found!" 1>&2
 		exit 1
-	else
-		_sflatest="$_calloutput"
-	fi
-	
-	if ! _calloutput=$(addmiscpath "timeout3" "$_timeout3") ; then
-		echo "$_calloutput" 1>&2
-		exit 1
-	else
-		_timeout3="$_calloutput"
 	fi
 fi
-
-function strtoarry(){
-	local _str _retarray _deli _c _l;_str=$1 _retarray=$2 _deli=$3
-	_c=-1;while read -r _l; do _c=$((_c+1));eval $_retarray[$_c]='$_l';done <<< "$(echo $_str | sed -e "s/$_deli/\n/g")"
-}
 
 echo "Querying installed.db file......."
 if [ ! -f "$_srcsbinpath/installed.db" ] ; then
@@ -117,7 +73,6 @@ fi
 
 echo "Querying apt-get ......."
 if "$_timeout3" -t 15 sudo echo ; then
-	echo "into apt-get ......."
 	_aptloc=$(command -v apt-get)
 	if [ ! -z "$_aptloc" ] ; then
 		echo "Available system updrages by apt-get:"
